table TeamList

	column 'id (Primary Key)'
		dataType: int64
		formatString: 0
		summarizeBy: none
		sourceColumn: id (Primary Key)

		annotation SummarizationSetBy = Automatic

		annotation Format = <Format Format="NumberWhole" Accuracy="0" />

		annotation DataTypeAtRefresh = Int64#####not a type

		annotation PBI_NameAtRefresh = id (Primary Key)

		annotation PBI_WasHiddenAtRefresh = False

	column Name
		dataType: string
		summarizeBy: none
		sourceColumn: Name

		annotation SummarizationSetBy = Automatic

		annotation Format = <Format Format="Text" />

		annotation DataTypeAtRefresh = String#####not a type

		annotation PBI_NameAtRefresh = Name

		annotation PBI_WasHiddenAtRefresh = False

	partition TeamList-4d4ab014-068a-460d-b3e9-c4f1b6a0335b = m
		mode: import
		source =
				let
				    #"UserName" = user_login,
				    #"Password" = user_password,
				    #"Header" = Binary.ToText(Text.ToBinary(#"UserName"&":" & #"Password")),
				    #"BaseURL" = url_list_team_name_itop,
				    Source = Web.Page(Web.Contents(#"BaseURL", [Headers=[Authorization="Basic " & #"Header"]])),
				    Data0 = Source{0}[Data],
				    #"En-têtes promus" = Table.PromoteHeaders(Data0, [PromoteAllScalars=true]),
				    #"Type modifié" = Table.TransformColumnTypes(#"En-têtes promus",{{"id (Primary Key)", Int64.Type}, {"Name", type text}})
				in
				    #"Type modifié"

	annotation PBI_DescriptionAtRefresh

	annotation PBI_ResultType = Table

